version: "3.8"

services:
  roach1:
    restart: "on-failure"
    image: cockroachdb/cockroach:v23.1.11
    container_name: node_roach1
    hostname: roach1
    networks:
      - "zitadel"
    ports:
      - "26257:26257"
      - "8081:8081"
    volumes:
      - roach1:/cockroach/cockroach-data
    command: >
      start
      --advertise-addr=roach1:26357
      --http-addr=roach1:8081
      --listen-addr=roach1:26357
      --sql-addr=roach1:26257
      --insecure
      --join=roach1:26357,roach2:26357,roach3:26357

  roach2:
    restart: "on-failure"
    image: cockroachdb/cockroach:v23.1.11
    container_name: node_roach2
    hostname: roach2
    networks:
      - "zitadel"
    ports:
      - "26258:26258"
      - "8082:8082"
    volumes:
      - roach2:/cockroach/cockroach-data
    command: >
      start
      --advertise-addr=roach2:26357
      --http-addr=roach2:8082
      --listen-addr=roach2:26357
      --sql-addr=roach2:26258
      --insecure
      --join=roach1:26357,roach2:26357,roach3:26357

  roach3:
    restart: "on-failure"
    image: cockroachdb/cockroach:v23.1.11
    container_name: node_roach3
    hostname: roach3
    networks:
      - "zitadel"
    ports:
      - "26259:26259"
      - "8083:8083"
    volumes:
      - roach3:/cockroach/cockroach-data
    command: >
      start
      --advertise-addr=roach3:26357
      --http-addr=roach3:8083
      --listen-addr=roach3:26357
      --sql-addr=roach3:26259
      --insecure
      --join=roach1:26357,roach2:26357,roach3:26357

  db-init:
    image: cockroachdb/cockroach:v23.1.11
    networks:
      - "zitadel"
    command: >
      init --host=roach1:26357 --insecure

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: "on-failure"
    networks:
      - "zitadel"
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MP_UI_AUTH: admin:admin
      MP_SMTP_AUTH: admin:admin

  zitadel:
    restart: "on-failure"
    networks:
      - "zitadel"
    image: "ghcr.io/zitadel/zitadel:latest"
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - "ZITADEL_DATABASE_COCKROACH_HOST=node_roach1"
      - "ZITADEL_EXTERNALSECURE=false"
      - "ZITADEL_EXTERNALDOMAIN=10.1.16.204"
      - "ZITADEL_EXTERNAL_PORT=8080"

    depends_on:
      - roach1
      - roach2
      - roach3
      - db-init
    ports:
      - "8080:8080"

networks:
  "zitadel":

volumes:
  data:
  roach1:
  roach2:
  roach3: